### PR TITLE
Prototype

### PR DESCRIPTION
**Pull request by Ahmed-Z-D**
The objective of this pull request is to address issue #1. This will be achieved by encapsulating the logic within the `app `directory into several functions. Additionally, a class will be included in `app.py`, which will be responsible for managing the menu.

It's important to keep in mind that the changes made are only a prototype at this stage. They are not yet suitable for use in real applications because the source code is fragile and requires handling many edge cases.

If you intend to add new features to the project, it's essential to take a few steps beforehand. First, you should consider improving the input statements to ensure that they are user-friendly and accurate. Additionally, converting the project into an installable package can make it easier to use and distribute. Finally, it's crucial to perform extensive testing on the existing functionalities to ensure their stability and reliability. By taking these precautions, you can increase the overall quality of the project and reduce the risk of introducing new issues.

Please note that the functionalities in` speedfeed.py` have not been restructured or implemented in the menu class yet. This is because of the way the logic is currently structured in that file, and it will need to be refactored before it can be integrated into the menu class.

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
I checked this out and tested it locally.  This definitely looks better and works to a much better degree.  I will definitely take your recommendations as the app improves.  

Approving for merge.

**Comment by gbowne1** [comment]
@Ahmed-Z-D Pylance did not like the Types.

**Comment by Ahmed-Z-D** [comment]
After running Mypy on the modified files, it appears that the types are correct and there are no type errors present. Can you provide more context on why Pylance flagged the types as incorrect?

**Comment by gbowne1** [comment]
Well for one thing I get:

```shell
$ python app.py
  File "app.py", line 7
    def _lathecalc(self) -> None:
                         ^
SyntaxError: invalid syntax
```

from line 7 of app.py

**Comment by gbowne1** [comment]
this appears anywhere you have this ->

**Comment by gbowne1** [comment]
This also reminds me that, when I do:

```shell
$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from app.lathecalc import lathe_calc
  File "/media/gbowne1/18656299-5992-400a-a7a4-b6ffc4b0612f/Documents/machinistcalc/app/lathecalc.py", line 6, in <module>
    ) -> tuple[float, float]:
TypeError: 'type' object is not subscriptable
```

**Comment by Ahmed-Z-D** [comment]
What version of Python are you using to execute the script?

**Comment by gbowne1** [comment]
$ python3 --version
Python 3.7.3

@@

$ python --version
Python 2.7.16

**Comment by Ahmed-Z-D** [comment]
> Well for one thing I get:
> 
> ```shell
> $ python app.py
>   File "app.py", line 7
>     def _lathecalc(self) -> None:
>                          ^
> SyntaxError: invalid syntax
> ```
> 
> from line 7 of app.py

Since type hints are not supported in Python 2.7.16, you encounter this error, on the other hand, Python 3.7.3 might mot support this syntax as shown here:



> This also reminds me that, when I do:
> 
> ```shell
> $ python3 app.py
> Traceback (most recent call last):
>   File "app.py", line 2, in <module>
>     from app.lathecalc import lathe_calc
>   File "/media/gbowne1/18656299-5992-400a-a7a4-b6ffc4b0612f/Documents/machinistcalc/app/lathecalc.py", line 6, in <module>
>     ) -> tuple[float, float]:
> TypeError: 'type' object is not subscriptable
> ```

A potential solution would be to replace `tuple `with `Tuple`, which is imported from the `typing `module.

If the problem continues, I will remove all type hints and immediately submit a new pull request.

P.S. run the script using `python3`

**Comment by gbowne1** [comment]
I did run it in 2 and 3 both just to be sure what was working and what wasn't as I like to be thorough.

I also noticed that my formatter wants to put the bendcalc import in the app.py at the top.  Noticed that when I looked at both the regular view and the working tree view.   And yes changing the capitalization fixed it.. but now has another error.

**Comment by Ahmed-Z-D** [comment]
> I did run it in 2 and 3 both just to be sure what was working and what wasn't as I like to be thorough.
> 
> I also noticed that my formatter wants to put the bendcalc import in the app.py at the top. Noticed that when I looked at both the regular view and the working tree view. And yes changing the capitalization fixed it.. but now has another error.

Can you provide more context on this error?

**Comment by gbowne1** [comment]
I had to reset my console/terminal.. might have just been a fluke. Sorry about that.  but yes, in /app/lathecalc.py fixing line #6 changing the capitalization of tuple to Tuple fixed it.  

I also noticed that running python3 app without the .py produced:

```shell
$ python3 app
/usr/bin/python3: can't find '__main__' module in 'app'
```

I have been experience with Plyint and Flake8 server keeps restarting.  

Running the app thouugh, I noticed some of the calculations are completely wrong, For instance a K factor value is not in inches.

**Comment by Ahmed-Z-D** [comment]
You can safely convert the unit of measurement for the K-factor to any desired unit without breaking the code.

**Comment by gbowne1** [comment]
Another strange thing happened when I pushed enter on the enter selection.

```shell
Select module to run:
1. Lathe Calculator
2. Sheet Metal Calculator
3. Bend Calculator


Enter selection: 
Traceback (most recent call last):
  File "app.py", line 104, in <module>
    Menu().run()
  File "app.py", line 96, in run
    selection = int(input("Enter selection: "))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by gbowne1** [comment]
K-Factor is a constant value, not a unit.  

When you bend sheet metal, the neutral axis shifts toward the inside surface of the bend. The K-factor is the ratio of the neutral axis location (t) to the material thickness (Mt)

**Comment by Ahmed-Z-D** [comment]
> Another strange thing happened when I pushed enter on the enter selection.
> 
> ```shell
> Select module to run:
> 1. Lathe Calculator
> 2. Sheet Metal Calculator
> 3. Bend Calculator
> 
> 
> Enter selection: 
> Traceback (most recent call last):
>   File "app.py", line 104, in <module>
>     Menu().run()
>   File "app.py", line 96, in run
>     selection = int(input("Enter selection: "))
> ValueError: invalid literal for int() with base 10: ''
> ```

As previously stated, the changes made are still in the prototype stage and the code is not yet robust. Therefore, to address this issue, you will need to focus on improving user inputs instead of relying on the fragility of the code.

In regards to the K-factor, you have the flexibility to modify its input description to suit your needs or preferences.

**Comment by gbowne1** [comment]
Ok, will work on some minor corrections.  Thank you. :-)

**Pull request merged**
